services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ecommerce-mailhog
    ports:
      - "1025:1025"
      - "38025:8025"
    networks:
      - ecommerce-network

  # redis:
  #   image: redis:7.2-alpine
  #   container_name: ecommerce-redis
  #   command: redis-server --appendonly yes
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped
  #   networks:
  #     - ecommerce-network
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  ecommerceapi:
    image: ecommerceapi
    build:
      context: .
      dockerfile: src/ECommerce.Api/Dockerfile
    ports:
      - "5000:8080" # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ecommerce_db;Database=ECommerceDB;User Id=sa;Password=Password123;TrustServerCertificate=True;
      # - Redis__ConnectionString=redis:6379,abortConnect=false
      - ASPNETCORE_URLS=http://+:8080;
    depends_on:
      # redis:
      #   condition: service_healthy
      ecommerce_db:
        condition: service_healthy

    networks:
      - ecommerce-network
    restart: on-failure

  ecommerce_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - ecommerce-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "Password123" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mssql_data:
  # redis-data:

networks:
  ecommerce-network:
    driver: bridge
