# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  ecommerceapi:
    image: ecommerceapi
    build:
      context: .
      dockerfile: src/ECommerce.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5162:5162
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  ecommerceadmin:
    image: ecommerceadmin
    build:
      context: .
      dockerfile: src/ECommerce.AdminPanel/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5163:5163
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
